### ISSUE TITLE
Create a stock module

### ISSUE THREAD

**Issue by invincibleelf** [DevOpsDistilled/OpERP#24]
develop basic stock module for inventory management

![stock](https://f.cloud.github.com/assets/3114757/824168/f26984c8-f03b-11e2-96fe-194dc2681a42.jpeg)

**Comment by koju** [comment]
What about this diagram?

A component to keep track of item quantity added and removed per date is required. (StockKeeper)

![stock module](https://f.cloud.github.com/assets/960364/827293/7f2e7ac8-f099-11e2-9b9b-ee9d9816a5ca.jpg)

**Comment by koju** [comment]
Stock ER Diagram with StockKeeper

StockKeeper.quantity is +ve for addition and -ve for stock deduction.

![stock module new er](https://f.cloud.github.com/assets/960364/827511/549e326c-f09e-11e2-9a35-d67db98968af.jpg)

**Comment by koju** [comment]
This diagram is more reasonable.

![stock module new er](https://f.cloud.github.com/assets/960364/829384/e180428c-f0d6-11e2-96cc-4cb625490c89.jpg)

**Comment by koju** [comment]
Simplifying the diagram.

![stock module new er simple](https://f.cloud.github.com/assets/960364/936105/bceb5136-009f-11e3-9809-15d3246fb41b.jpeg)

**Comment by invincibleelf** [comment]
this means no Stock keeper???
How to display total items in warehouse??

**Comment by koju** [comment]
We'll have to do some computations while displaying.
It better than doing processing with multiple entities when trying to update stock, Is it not?
